<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ValheimDiscordNotifier</AssemblyName>
    <RootNamespace>ValheimDiscordNotifier</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"
                      Version="1.0.3"
                      PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild"
                      Version="0.5.0-beta.2"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
